# Generated by Django 5.2.3 on 2025-07-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_problem_submission_testcase_submissiontestcaseresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
