# Generated by Django 5.2.3 on 2025-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_problem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
